services:
  backend:
    container_name: backend
    hostname: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "19999:8000"
    env_file:
      - .env
    command: |
      sh -c "
      uv run -m uvicorn main:app --host "0.0.0.0" --reload 
      "
    networks:
      - main_network

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend/app:/app
    ports:
      - "20000:8000"
    env_file:
      - .env
    command: |
      sh -c "
      uv run -m uvicorn main:app --host "0.0.0.0" --reload 
      "
    networks:
      - main_network

networks:
  main_network:
    driver: bridge